# Generated by Django 4.1.7 on 2023-04-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areavisitstatistic',
            name='age_group',
            field=models.CharField(choices=[(10, 'ten'), (20, 'twenty'), (30, 'thirty'), (40, 'forty'), (50, 'fifty')], default=20, max_length=31),
        ),
        migrations.AlterField(
            model_name='areavisitstatistic',
            name='companion',
            field=models.CharField(choices=[('family', 'family'), ('not_family', 'not_family'), ('family_w_child', 'family_with_child')], default='not_family', max_length=31),
        ),
    ]
